In [1]:
%pip install numpy

In [5]:
import numpy as np

# 1. Create

In [6]:
data = np.random.rand(2,3,4)
data

array([[[0.43314054, 0.3867334 , 0.98854595, 0.84852843],
        [0.09829862, 0.03092364, 0.99933892, 0.49870903],
        [0.43401593, 0.6172488 , 0.99591604, 0.25780789]],

       [[0.74357521, 0.14304989, 0.61595625, 0.66074645],
        [0.83914175, 0.12267988, 0.28607434, 0.43733293],
        [0.7337208 , 0.38652294, 0.9286377 , 0.23101375]]])

In [7]:
zeros = np.zeros((2,3,4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [8]:
ones = np.ones((2,3,4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
full = np.full((2,3,4), 7)
full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [11]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [12]:
# get specific row
arr[1,:]

array([5, 6, 7, 8])

In [13]:
# get specific col
arr[:, 2]

array([3, 7])

In [14]:
# getting a little more fancy [startindex:endindex:stepsize]
arr[1:, 1 : : 2]

array([[6, 8]])

In [15]:
arr[1, : -1]

array([5, 6, 7])

In [16]:
three_arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
three_arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [17]:
three_arr[:,1,:]

array([[4, 5, 6]])

In [21]:
full_like = np.full_like(three_arr, 99)
full_like

array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]]])

In [22]:
# random Integer values
np.random.randint(-3, 4, size=(3,5))

array([[ 2,  3,  3, -2,  0],
       [-3,  3,  3, -1, -3],
       [ 3,  0, -2, -3,  2]])

In [23]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
# repeat arr
arr = np.array([[1,2,3]])
np.repeat(arr, 4, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [25]:
output = np.ones((5,5))
print(output, '\n')
z = np.zeros((3,3))
print(z, '\n')
z[1,1] = 9
print(z, '\n')
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
# vertical stack
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [40]:
# horizontal stack

h1 = np.ones((2,3))
h2 = np.zeros_like(h1)

np.hstack([h2, h1, h1, h2])

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0.]])

# 2. Read

In [26]:
data.shape

(2, 3, 4)

In [20]:
data.size

24

In [21]:
data.dtype

dtype('float64')

In [22]:
new_arr = data[0]
new_arr

array([[0.59387605, 0.31703629, 0.88204991, 0.01345226],
       [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
       [0.87508723, 0.00672746, 0.04659363, 0.92256918]])

In [24]:
slicer = data[0:2]
slicer

array([[[0.59387605, 0.31703629, 0.88204991, 0.01345226],
        [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
        [0.87508723, 0.00672746, 0.04659363, 0.92256918]],

       [[0.77266068, 0.99477646, 0.03765304, 0.99894915],
        [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
        [0.00408406, 0.81291357, 0.63577107, 0.25183203]]])

In [28]:
last_arr = data[-1]
last_arr

array([[0.77266068, 0.99477646, 0.03765304, 0.99894915],
       [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
       [0.00408406, 0.81291357, 0.63577107, 0.25183203]])

In [27]:
single_val = data[0][0][0]
single_val

0.5938760539655104

# 3. Update

In [30]:
list1 = np.random.rand(10)
list2  = np.random.rand(10)

In [32]:
# copy array content, not variable pointer
list3_copy = list1.copy()
list3_copy

array([0.17731471, 0.06758824, 0.53798834, 0.26087195, 0.89135543,
       0.59278924, 0.71140224, 0.06194649, 0.89530845, 0.57099054])

In [30]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [37]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,5)
log = np.log(25)
exp = np.exp([2, 3])
min = np.min(list1)
max = np.max(list1)

In [38]:
data

array([[[0.59387605, 0.31703629, 0.88204991, 0.01345226],
        [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
        [0.87508723, 0.00672746, 0.04659363, 0.92256918]],

       [[0.77266068, 0.99477646, 0.03765304, 0.99894915],
        [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
        [0.00408406, 0.81291357, 0.63577107, 0.25183203]]])

In [39]:
data[0][0][2] = 777

In [40]:
data

array([[[5.93876054e-01, 3.17036288e-01, 7.77000000e+02, 1.34522597e-02],
        [4.25432720e-02, 6.79537908e-01, 9.32610405e-01, 5.03578157e-01],
        [8.75087230e-01, 6.72745670e-03, 4.65936279e-02, 9.22569179e-01]],

       [[7.72660678e-01, 9.94776456e-01, 3.76530448e-02, 9.98949147e-01],
        [9.48687388e-01, 6.93161826e-01, 5.55311032e-01, 4.57225024e-02],
        [4.08405542e-03, 8.12913574e-01, 6.35771065e-01, 2.51832027e-01]]])

In [41]:
data.sort()
data

array([[[1.34522597e-02, 3.17036288e-01, 5.93876054e-01, 7.77000000e+02],
        [4.25432720e-02, 5.03578157e-01, 6.79537908e-01, 9.32610405e-01],
        [6.72745670e-03, 4.65936279e-02, 8.75087230e-01, 9.22569179e-01]],

       [[3.76530448e-02, 7.72660678e-01, 9.94776456e-01, 9.98949147e-01],
        [4.57225024e-02, 5.55311032e-01, 6.93161826e-01, 9.48687388e-01],
        [4.08405542e-03, 2.51832027e-01, 6.35771065e-01, 8.12913574e-01]]])

In [42]:
data.shape

(2, 3, 4)

In [43]:
data_n_shape = data.reshape((2,2,-1))
data_n_shape.shape

(2, 2, 6)

In [49]:
zeros = np.zeros(6)
print(zeros, '\n')
zeros = np.append(zeros, [44, 89])
print(zeros, '\n')
zeros = np.insert(zeros, 1, 77)
print(zeros)

[0. 0. 0. 0. 0. 0.] 

[ 0.  0.  0.  0.  0.  0. 44. 89.] 

[ 0. 77.  0.  0.  0.  0.  0. 44. 89.]


# 4. Delete

In [50]:
data

array([[[1.34522597e-02, 3.17036288e-01, 5.93876054e-01, 7.77000000e+02],
        [4.25432720e-02, 5.03578157e-01, 6.79537908e-01, 9.32610405e-01],
        [6.72745670e-03, 4.65936279e-02, 8.75087230e-01, 9.22569179e-01]],

       [[3.76530448e-02, 7.72660678e-01, 9.94776456e-01, 9.98949147e-01],
        [4.57225024e-02, 5.55311032e-01, 6.93161826e-01, 9.48687388e-01],
        [4.08405542e-03, 2.51832027e-01, 6.35771065e-01, 8.12913574e-01]]])

In [51]:
data.shape

(2, 3, 4)

In [55]:
data = np.delete(data, 0, axis=1)

In [56]:
data.shape

(2, 2, 4)

In [57]:
data

array([[[0.04254327, 0.50357816, 0.67953791, 0.9326104 ],
        [0.00672746, 0.04659363, 0.87508723, 0.92256918]],

       [[0.0457225 , 0.55531103, 0.69316183, 0.94868739],
        [0.00408406, 0.25183203, 0.63577107, 0.81291357]]])

In [61]:
import os
!mkdir exports
np.save(os.path.join('exports', 'data_test_arr.npy'), data)

2206.00s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
mkdir: exports: File exists


In [62]:
test = np.load(os.path.join('exports', 'data_test_arr.npy'))
test

array([[[0.04254327, 0.50357816, 0.67953791, 0.9326104 ],
        [0.00672746, 0.04659363, 0.87508723, 0.92256918]],

       [[0.0457225 , 0.55531103, 0.69316183, 0.94868739],
        [0.00408406, 0.25183203, 0.63577107, 0.81291357]]])

# Load from file

In [52]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [47]:
filedata > 30

array([[False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [49]:
# arr indexing with conditional
filedata[filedata > 40]

array([196,  75,  42, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [56]:
 np.any(filedata > 40, axis=0)

array([False,  True, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [59]:
np.all(filedata > 40, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [60]:
np.all(filedata > 0, axis=1)

array([False, False, False])

In [61]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [62]:
# ~ -> not
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [68]:
demoarr = np.arange(1,31).reshape((6,5))
print(demoarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [72]:
demoarr[2:4,:2]

array([[11, 12],
       [16, 17]])

In [84]:
demoarr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [88]:
print(demoarr[[0,4,5], 3:])

[ 4  5 24 25 29 30]
[[ 4  5]
 [24 25]
 [29 30]]
