In [1]:
%pip install numpy

In [2]:
import numpy as np

# 1. Create

In [9]:
data = np.random.rand(2,3,4)
data

array([[[0.59387605, 0.31703629, 0.88204991, 0.01345226],
        [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
        [0.87508723, 0.00672746, 0.04659363, 0.92256918]],

       [[0.77266068, 0.99477646, 0.03765304, 0.99894915],
        [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
        [0.00408406, 0.81291357, 0.63577107, 0.25183203]]])

In [13]:
zeros = np.zeros((2,3,4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
ones = np.ones((2,3,4))
ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
full = np.full((2,3,4), 7)
full

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [18]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 2. Read

In [19]:
data.shape

(2, 3, 4)

In [20]:
data.size

24

In [21]:
data.dtype

dtype('float64')

In [22]:
new_arr = data[0]
new_arr

array([[0.59387605, 0.31703629, 0.88204991, 0.01345226],
       [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
       [0.87508723, 0.00672746, 0.04659363, 0.92256918]])

In [24]:
slicer = data[0:2]
slicer

array([[[0.59387605, 0.31703629, 0.88204991, 0.01345226],
        [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
        [0.87508723, 0.00672746, 0.04659363, 0.92256918]],

       [[0.77266068, 0.99477646, 0.03765304, 0.99894915],
        [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
        [0.00408406, 0.81291357, 0.63577107, 0.25183203]]])

In [28]:
last_arr = data[-1]
last_arr

array([[0.77266068, 0.99477646, 0.03765304, 0.99894915],
       [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
       [0.00408406, 0.81291357, 0.63577107, 0.25183203]])

In [27]:
single_val = data[0][0][0]
single_val

0.5938760539655104

# 3. Update

In [29]:
list1 = np.random.rand(10)
list2  = np.random.rand(10)

In [30]:
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [37]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,5)
log = np.log(25)
exp = np.exp([2, 3])
min = np.min(list1)
max = np.max(list1)

In [38]:
data

array([[[0.59387605, 0.31703629, 0.88204991, 0.01345226],
        [0.04254327, 0.67953791, 0.9326104 , 0.50357816],
        [0.87508723, 0.00672746, 0.04659363, 0.92256918]],

       [[0.77266068, 0.99477646, 0.03765304, 0.99894915],
        [0.94868739, 0.69316183, 0.55531103, 0.0457225 ],
        [0.00408406, 0.81291357, 0.63577107, 0.25183203]]])

In [39]:
data[0][0][2] = 777

In [40]:
data

array([[[5.93876054e-01, 3.17036288e-01, 7.77000000e+02, 1.34522597e-02],
        [4.25432720e-02, 6.79537908e-01, 9.32610405e-01, 5.03578157e-01],
        [8.75087230e-01, 6.72745670e-03, 4.65936279e-02, 9.22569179e-01]],

       [[7.72660678e-01, 9.94776456e-01, 3.76530448e-02, 9.98949147e-01],
        [9.48687388e-01, 6.93161826e-01, 5.55311032e-01, 4.57225024e-02],
        [4.08405542e-03, 8.12913574e-01, 6.35771065e-01, 2.51832027e-01]]])

In [41]:
data.sort()
data

array([[[1.34522597e-02, 3.17036288e-01, 5.93876054e-01, 7.77000000e+02],
        [4.25432720e-02, 5.03578157e-01, 6.79537908e-01, 9.32610405e-01],
        [6.72745670e-03, 4.65936279e-02, 8.75087230e-01, 9.22569179e-01]],

       [[3.76530448e-02, 7.72660678e-01, 9.94776456e-01, 9.98949147e-01],
        [4.57225024e-02, 5.55311032e-01, 6.93161826e-01, 9.48687388e-01],
        [4.08405542e-03, 2.51832027e-01, 6.35771065e-01, 8.12913574e-01]]])

In [42]:
data.shape

(2, 3, 4)

In [43]:
data_n_shape = data.reshape((2,2,-1))
data_n_shape.shape

(2, 2, 6)

In [49]:
zeros = np.zeros(6)
print(zeros, '\n')
zeros = np.append(zeros, [44, 89])
print(zeros, '\n')
zeros = np.insert(zeros, 1, 77)
print(zeros)

[0. 0. 0. 0. 0. 0.] 

[ 0.  0.  0.  0.  0.  0. 44. 89.] 

[ 0. 77.  0.  0.  0.  0.  0. 44. 89.]


# 4. Delete

In [50]:
data

array([[[1.34522597e-02, 3.17036288e-01, 5.93876054e-01, 7.77000000e+02],
        [4.25432720e-02, 5.03578157e-01, 6.79537908e-01, 9.32610405e-01],
        [6.72745670e-03, 4.65936279e-02, 8.75087230e-01, 9.22569179e-01]],

       [[3.76530448e-02, 7.72660678e-01, 9.94776456e-01, 9.98949147e-01],
        [4.57225024e-02, 5.55311032e-01, 6.93161826e-01, 9.48687388e-01],
        [4.08405542e-03, 2.51832027e-01, 6.35771065e-01, 8.12913574e-01]]])

In [51]:
data.shape

(2, 3, 4)

In [55]:
data = np.delete(data, 0, axis=1)

In [56]:
data.shape

(2, 2, 4)

In [57]:
data

array([[[0.04254327, 0.50357816, 0.67953791, 0.9326104 ],
        [0.00672746, 0.04659363, 0.87508723, 0.92256918]],

       [[0.0457225 , 0.55531103, 0.69316183, 0.94868739],
        [0.00408406, 0.25183203, 0.63577107, 0.81291357]]])

In [61]:
import os
!mkdir exports
np.save(os.path.join('exports', 'data_test_arr.npy'), data)

2206.00s - pydevd: Sending message related to process being replaced timed-out after 5 seconds
mkdir: exports: File exists


In [62]:
test = np.load(os.path.join('exports', 'data_test_arr.npy'))
test

array([[[0.04254327, 0.50357816, 0.67953791, 0.9326104 ],
        [0.00672746, 0.04659363, 0.87508723, 0.92256918]],

       [[0.0457225 , 0.55531103, 0.69316183, 0.94868739],
        [0.00408406, 0.25183203, 0.63577107, 0.81291357]]])